name: NPM Publish

on: push

jobs:
  publish:
    runs-on: ubuntu-latest
    outputs:
      publish-status: ${{ steps.publish.outputs.type }}
      publish-version: ${{ steps.publish.outputs.version }}
      publish-old-version: ${{ steps.publish.outputs.old-version }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: yarn install
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
  success-publish:
    needs: publish
    runs-on: ubuntu-latest
    if: needs.publish.outputs.publish-status != 'none'
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'New NPM version has been published (${{ needs.publish.outputs.publish-old-version }} => ${{ needs.publish.outputs.publish- }})'
